### ISSUE TITLE
Is it possibility bind exist object to nullc?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WheretIB/nullc#11]
```
Is it possibility bind an existed object to nullc?
And is there any way can bind an existed c++ calss member variables to nullc?
```

Original issue reported on code.google.com by `jiangluo...@gmail.com` on 15 Mar 2012 at 2:08

**Comment by WheretIB** [comment]
This issue is closed by https://github.com/WheretIB/nullc/commit/544c78ad58f9c66d0b15f66dcd878c5aa38c65df
