### ISSUE TITLE
Where can I find documentation?

### ISSUE THREAD

**Issue by t0md3an** [WheretIB/nullc#25]
@zeux @WheretIB

**Comment by WheretIB** [comment]
Hello t0md3an,

Language reference is available here on Github wiki at https://github.com/WheretIB/nullc/wiki/Language-Reference
Library C/C++ API reference is available at https://github.com/WheretIB/nullc/wiki/Library-Reference

Both wiki pages are available in the LanguageEN.html and LibraryEN.html files inside the repository, but wiki pages contain more recent updates.

**Comment by t0md3an** [comment]
Thanks @WheretIB , also I have a question, is there any of `fprintf`/`printf`/`snprintf` in nullc like in libc?

**Comment by WheretIB** [comment]
1. std.io module https://github.com/WheretIB/nullc/wiki/Language-Reference#stdio contains the current way of doing I/O, although I myself like C functions more. It's something I'm looking at providing in the future.
2. There is no using for namespaces in nullc
3. I've gotten this request before and it's also something nice to have for standalone apps but it's not available right now, sorry.
4. std.io Input function is the low-level primitive for getting characters.
