### ISSUE TITLE
Question: nullC just translates to C?

### ISSUE THREAD

**Issue by t0md3an** [WheretIB/nullc#26]
@WheretIB 

> nullcl/nullcl -x a.out file.nc

```
../NULLC/translation/runtime.cpp:7:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
```

**Comment by t0md3an** [comment]
yes

**Comment by WheretIB** [comment]
Sorry for the late reply, nullc translation to C/C++ is a secondary target, the main focus for the language is scripting similar to Lua/AngelScript and others.

Having said that, I've added a fix for this non-standard include file and for a link error that came from a recent change to the runtime, so code translated to C/C++ should build and run now.
