### ISSUE TITLE
Makefile patch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WheretIB/nullc#8]
```
A fairly trivial patch to the Makefile to include C++ translation.
```

Original issue reported on code.google.com by `Conrad.S...@gmail.com` on 23 Sep 2010 at 4:44

Attachments:
- [Makefile.diff](https://storage.googleapis.com/google-code-attachments/nullc/issue-8/comment-0/Makefile.diff)

**Comment by WheretIB** [comment]
Fixed in reg_vm branch
